### ISSUE TITLE
delay discounting plots interpretation

### ISSUE THREAD

**Issue by JingyiWangCatherine** [drbenvincent/delay-discounting-analysis#216]
Hello Dr. Vincent, 

Thank you for creating this amazing toolbox and made it availble to the public. 

I used your toolbox with our delay discounting experiment. It seems working perfectly. 

But I have trouble identifying the meaning of the gray dots in the discounting plots for each participants. I assume the white dots are trials with LL choices and the gray dots are trials with SS choices. Please correct me if I am wrong. 

Thank you.

**Comment by drbenvincent** [comment]
Sorry for the slow reply, I've moved away from Matlab so don't maintain this as much as I used to.

Yes, data points represent answers to individual discounting questions. The colour codes what that choice was. Points above the line correspond to SS rewards and points below the line correspond to LL rewards. If that doesn't quite answer your question, feel free to drop in a screenshot so I can see exactly what you mean.

**Comment by JingyiWangCatherine** [comment]
Hello Dr. Vincent,

Thank you for getting back to me. What I was confused about is the meaning
of the gray dots in the plots. I think the white dots are trials choosing
sooner rewards and the black dots are trials choosing later rewards right?
Please see the sample plots below:
[image: grid_discount_functions-separateLogK.png]
Thanks a lot!

Jingyi

**Comment by drbenvincent** [comment]
I can't see the image. If you drag it into the tex box on GitHub, then that should work

**Comment by JingyiWangCatherine** [comment]
Here is the plots! Sorry ~

My question is what are the gray dots?
![grid_discount_functions-separateLogK](https://user-images.githubusercontent.com/80180208/126365353-9120b744-9378-4377-a967-bd0667918d8b.png)

**Comment by drbenvincent** [comment]
Thanks. I remember now.

The colour represents the proportion of times someone chose immediate. So for sets of delay discounting questions which have some questions repeated, then there is the potential for people to respond the same way, or not.

So black here represents an immediate choice - you can see that because the person on the bottom right hardly discounts the future at all, many of their points are white, so they mostly chose delayed options.

Let me know if you have any more questions - otherwise feel free to close the issue :)

**Comment by JingyiWangCatherine** [comment]
Hello Dr. Vincent:

Thank you so much for your answer! But I am still confused about the following: If each dot is a datapoint (trial/question), and the color code is “black dot”=“smaller sooner” and “white dot”= “larger later”, what would the gray be? (Unless I am misunderstanding and each datapoint is not an individual trial). 

Thanks again for your help and invaluable resource!

**Comment by drbenvincent** [comment]
Each data point is an individual trial. But it looks like your set of discounting questions may contain multiple instances of the same question. For example, your discounting questions may have "$100 now or $110 in 7 days" more than once. When this happens then the data points will be in the same place on the graph. So what do we do when one on trial someone opts for the smaller sooner reward and the other time they are asked the same question they opt for the larger later reward? What colour should the dot be? The solution I used was to use grayscale to represent the proportion of times that someone answered a particular way.

It might be worth looking through your dataset, maybe ordering the questions, from what I can tell you have duplicate discounting questions in there. This can be useful because if you ask questions on or near the indifference point then peoples' responses will vary.

**Comment by JingyiWangCatherine** [comment]
Hello Dr. Vincent,

This is super helpful. I do have repeated questions. Do you think it is
uncommon or not good to have repeated questions? Thanks a million.

Jingyi

**Comment by drbenvincent** [comment]
I don't think there is a right or wrong. I think it depends on your research goals.

**Comment by JingyiWangCatherine** [comment]
Thank you so much Dr. Vincent. This is so helpful. I will close the thread now. 

Jingyi
