### ISSUE TITLE
Ebert-Prelec Constant Sensitivity model

### ISSUE THREAD

**Issue by JingyiWangCatherine** [drbenvincent/delay-discounting-analysis#217]
Dear Dr. Vincent, 

Your beautiful toolbox worked very well with our delay discounting task. Thank you for developing this amazing toolbox. I would like to ask whether this toolbox also has the Ebert-prelect constatnt sensitivity model. If it does, what's the model I should call for. 

Best,

**Comment by drbenvincent** [comment]
Hi. So that discount function is not implemented at the moment. For the moment I've stopped developing the toolbox as I've moved away from Matlab. Depending on your level of experience, you may be able to implement it yourself. Otherwise, if it was crucial then we could potentially collaborate with some Python code?
