### ISSUE TITLE
DataClass error

### ISSUE THREAD

**Issue by DAOConnor** [drbenvincent/delay-discounting-analysis#33]
Hi Ben

Thank you very much for making this great code available to other researchers. I'm just trying to run the demo as you describe it in your youtube video and I'm running into a problem that I can't seem to fix. It may well be down to my lack of matlab experience, but I thought I'd post a question about it here to see if you could offer any suggestions. Perhaps it is a basic oversight on my part so I've pasted the code that I ran below. The error relates to data object that you say shoud be created.  In your basic script it is called 'methodspaper-kirby27.txt'. When I run this script, I get this error: 

??? Error using ==> DataClass
Too many input arguments.

Error in ==> test at 6
myData = DataClass('methodspaper-kirby27.txt','data');

Script:

% cd to project folder
cd('C:\Users\Desktop\delay_discounting_code\delay-discounting-analysis-master\demo');
% define toolbox location
toolboxPath = setToolboxPath('C:\Users\Desktop\delay_discounting_code\delay-discounting-analysis-master\ddToolbox');
% load data
myData = DataClass('methodspaper-kirby27.txt','data');
myData.loadDataFiles({'AC-kirby27-DAYS.txt','CS-kirby27-DAYS.txt','NA-kirby27-DAYS.txt','SB-kirby27-DAYS.txt'});
% construct a model and change some option
hModel = ModelHierarchical(toolboxPath, 'JAGS', myData);
hModel.sampler.setMCMCtotalSamples(10^5);
hModel.sampler.setMCMCnumberOfChains(2);
% conduct inference
hModel.conductInference();
%examine results
hModel.exportParameterEstimates();
hModel.plot();

**Comment by drbenvincent** [comment]
Hi
I hope it's of use to you. So this should be a simple issue to resolve, although I've not tested with a PC, so there could be some more saving issues later, let me know if so.

We can resolve this pretty simply... basically there are two lines in your code which create objects in the 'old' way before I updated the code at a certain point. So I'll assume you've got, or will download the latest version. Let me know if this doesn't work...

``` matlab
% cd to project folder
cd('C:\Users\Desktop\delay_discounting_code\delay-discounting-analysis-master\demo');
% define toolbox location
toolboxPath = setToolboxPath('C:\Users\Desktop\delay_discounting_code\delay-discounting-analysis-master\ddToolbox');
% load data
myData = DataClass('data');
myData.loadDataFiles({'AC-kirby27-DAYS.txt','CS-kirby27-DAYS.txt','NA-kirby27-DAYS.txt','SB-kirby27-DAYS.txt'});
% construct a model and change some option
hModel = ModelHierarchical(toolboxPath, 'JAGS', myData, 'saveFolder');
hModel.sampler.setMCMCtotalSamples(10^3);
hModel.sampler.setMCMCnumberOfChains(2);
% conduct inference
hModel.conductInference();
%examine results
hModel.exportParameterEstimates();
hModel.plot();
```

The lines changed were

```
myData = DataClass('data');
```

and

```
hModel = ModelHierarchical(toolboxPath, 'JAGS', myData, 'saveFolder');
```

I'm trying to not change how this setup script works because of exactly this kind of problem. But in situations where you run multiple analyses on the same dataset it makes more sense to do it the new way, that is, to define the save folder in the model. Anyway, reasons aren'y so important, but hopefully this all works now

Let me know how you get on.
Ben

**Comment by DAOConnor** [comment]
Hi Ben

Thanks very much for getting back to me so quickly and with such a thorough reply. So I just tried your amended script and I got a different error (which is progress I guess!). Also, the version of your code that I have is the latest you have available to download as a zip file from this site. Any more advice would be great!. The output is below. 

Cheers
David

??? Undefined function or variable 'table'.

Error in ==> DataClass>DataClass.DataClass at 26
            obj.groupTable = table();

Error in ==> test at 6
myData = DataClass('data');

**Comment by drbenvincent** [comment]
No problem. Sorry about the roadblock to using the code.
The issue seems to be initialising an empty Matlab table, so this could be a Matlab version issue. What version are you running? If you type `table()` into the matlab command window, do you get an error?

I'll run through it all on a PC to check there aren't issues on that front, but it will take me a few days to get hold of one.

**Comment by DAOConnor** [comment]
Thanks again for your prompt reply. So when I type table() into matlab I get the output, which is below. My desktop has quite an old version of matlab (2010) though. I just managed to get on to the 2013a version that we have on the server and the same problem occurred. That is, the same error when I run the script and the same ouput when I type table() into the command window. 

Sorry to keep bothering you about this problem. Any further ideas would be greatly appreciated. 

> > table()
> > Undefined function or variable 'table'.

PS Having googled this problem. It seems that the earliest version to have table available is 2013a
http://www.mathworks.com/matlabcentral/answers/167018-which-numeric-type-works-for-function-table

**Comment by drbenvincent** [comment]
It's not a problem, this is my first 'big' bit of code I am releasing into the wild, so I'm happy to make sure it works for people. And it's not going to hurt the citation count of the paper :)

So sure it seems a pretty straight forward Matlab version issue. The options are either:
- upgrade to a newer version of Matlab :)
- I could subclass `DataClass` to make a version which doesn't use Matlab tables. I might be able to fit this in next week.

I realise this is one of the downsides of Matlab. I'm doing an extremely slow transition over to using Python where everything is free, but a Python implementation of this toolbox is not a small job. I've been considering this for a while, partly as a way to commit to learning Python properly, but this is something for the future.

See how you get on with updating Matlab version if possible, but otherwise I hope to resolve this next week at some point.

**Comment by DAOConnor** [comment]
Yeah unfortunately, I doubt that my lab will update Matlab soon. They are quite strict about those things here in France. What a shame it is so expensive!

It would be great if you could amend your code, but I would also fully understand if you don't have the time to tailor your code for every single user's needs ;)

Hopefully more researchers will start switching to Python. FYI you probably know of him already but Thomas Wiecki (https://github.com/twiecki) has a lot of Python code available that uses Bayes to analyse choice data. I've never used his code but I saw him give a talk recently and he was very passionate about using Python in science!

**Comment by drbenvincent** [comment]
I've seen a talk of his on YouTube about PyMC which is a great looking package for doing inference direct in Python rather than having a separate package like JAGS. I'll get to Python eventually! But first on the list is to port the JAGS models to STAN. I've been having a bit of trouble fitting one of my other datasets with JAGS and suspect the sampling in STAN will solve these problems.

Anyway, I'll post back here when I get time to make the code backward compatible.

**Comment by drbenvincent** [comment]
Ok. That last commit (in the dev branch) should get around the fact that old Matlab versions don't have tables. You need to replace `DataClass` for `DataClassLegacy` in your setup script. That should fix the immediate problem you were having. So you change from this

```
myData = DataClass(pathToData);
```

to this

```
myData = DataClassLegacy(pathToData);
```

Although we may well find more problems with older Matlab version. In particular, the code does require the Statistics Toolbox (recently renamed to Statistics and Machine Learning Toolbox). Try it and see.

If you are not that familiar with GitHub or don't use the GitHub Desktop app, you can go to the main repository page > look for a button called "Branch: master" and change it to "Branch: dev". You can then download as a zip. That should give you the latest version. I'm waiting until I've done a few more things until I do another proper release.

**Comment by DAOConnor** [comment]
Great! Thanks very much for updating this. I will let you know how it goes once I try it.

**Comment by drbenvincent** [comment]
Closing this issue, as it wasn't a bug as such. Just we require Matlab 2015 or later
